Use the the steps in the tutorial:
https://towardsdatascience.com/access-data-from-twitter-api-using-r-and-or-python-b8ac342d3efe

(It will take time for the activation!)

Now choose someone’s twitter as a target, scrape it and analyze the following points:

1: Frequency of tweets (You’re free to choose a daily/weekly/monthly timeframe 
                        accordingly to the case)

2: Top 5 most used hashtags

3: Choose a relevant keyword and report how many times it has been used in the tweets 
    that you scraped ( Ex: for Trump’s twitter you can search for “Wall” or “elections”)

In [1]:
import json
from twython import Twython

with open("credentials.json") as infile:
    credentials = json.load(infile)

twitter_client = Twython(credentials["consumer_key"],
                         credentials["consumer_secret"],
                         credentials["access_token"],
                         credentials["access_token_secret"])

In [16]:
import itertools

In [20]:
import collections

The twitter_client variable holds the Twython object which allows us to access different information for different API endpoints (https://developer.twitter.com/en/docs.html). As an example, we can reveal information about the Propulsion Academy Twitter account. Calling the .show_user() method we can display a dictionary containing certain attributes associated with the account:

In [2]:
twitter_client.show_user(screen_name = "TheRock")

{'id': 250831586,
 'id_str': '250831586',
 'name': 'Dwayne Johnson',
 'screen_name': 'TheRock',
 'location': '',
 'profile_location': None,
 'description': 'Chivalrous gentleman.. just add fine tequila.',
 'url': None,
 'entities': {'description': {'urls': []}},
 'protected': False,
 'followers_count': 14003415,
 'friends_count': 270,
 'listed_count': 31877,
 'created_at': 'Fri Feb 11 22:14:10 +0000 2011',
 'favourites_count': 284,
 'utc_offset': None,
 'time_zone': None,
 'geo_enabled': False,
 'verified': True,
 'statuses_count': 23913,
 'lang': None,
 'status': {'created_at': 'Mon Nov 18 23:30:09 +0000 2019',
  'id': 1196571324367429640,
  'id_str': '1196571324367429640',
  'text': 'Update from the video I posted. \nLook at this lil’ boy, Hyrum’s face. \nThat’s some joy real right there. \nThank you… https://t.co/XyS5wZMqWQ',
  'truncated': True,
  'entities': {'hashtags': [],
   'symbols': [],
   'user_mentions': [],
   'urls': [{'url': 'https://t.co/XyS5wZMqWQ',
     'expanded_url': 'https://twitter.com/i/web/status/1196571324367429640',
     'display_url': 'twitter.com/i/web/status/1…',
     'indices': [117, 140]}]},
  'source': '<a href="http://instagram.com" rel="nofollow">Instagram</a>',
  'in_reply_to_status_id': None,
  'in_reply_to_status_id_str': None,
  'in_reply_to_user_id': None,
  'in_reply_to_user_id_str': None,
  'in_reply_to_screen_name': None,
  'geo': None,
  'coordinates': None,
  'place': None,
  'contributors': None,
  'is_quote_status': False,
  'retweet_count': 153,
  'favorite_count': 2409,
  'favorited': False,
  'retweeted': False,
  'possibly_sensitive': False,
  'lang': 'en'},
 'contributors_enabled': False,
 'is_translator': False,
 'is_translation_enabled': True,
 'profile_background_color': '131516',
 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme14/bg.gif',
 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme14/bg.gif',
 'profile_background_tile': True,
 'profile_image_url': 'http://pbs.twimg.com/profile_images/3478244961/01ebfc40ecc194a2abc81e82ab877af4_normal.jpeg',
 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/3478244961/01ebfc40ecc194a2abc81e82ab877af4_normal.jpeg',
 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/250831586/1572635095',
 'profile_link_color': '1B95E0',
 'profile_sidebar_border_color': '000000',
 'profile_sidebar_fill_color': 'C7C7C7',
 'profile_text_color': '333333',
 'profile_use_background_image': False,
 'has_extended_profile': True,
 'default_profile': False,
 'default_profile_image': False,
 'can_media_tag': False,
 'followed_by': False,
 'following': False,
 'follow_request_sent': False,
 'notifications': False,
 'translator_type': 'regular'}

In [3]:
pip install python-twitter

Requirement already satisfied: python-twitter in /Users/timothypillow/anaconda3/lib/python3.7/site-packages (3.5)
Requirement already satisfied: requests in /Users/timothypillow/anaconda3/lib/python3.7/site-packages (from python-twitter) (2.22.0)
Requirement already satisfied: future in /Users/timothypillow/anaconda3/lib/python3.7/site-packages (from python-twitter) (0.18.2)
Requirement already satisfied: requests-oauthlib in /Users/timothypillow/anaconda3/lib/python3.7/site-packages (from python-twitter) (1.2.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/timothypillow/anaconda3/lib/python3.7/site-packages (from requests->python-twitter) (1.24.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/timothypillow/anaconda3/lib/python3.7/site-packages (from requests->python-twitter) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/timothypillow/anaconda3/lib/python3.7/site-packages (from requests->python-twitter) (2018.11.29)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/timothypillow/anaconda3/lib/python3.7/site-packages (from requests->python-twitter) (2.8)
Requirement already satisfied: oauthlib>=3.0.0 in /Users/timothypillow/anaconda3/lib/python3.7/site-packages (from requests-oauthlib->python-twitter) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [23]:
#!/usr/bin/env python
# encoding: utf-8

import tweepy #https://github.com/tweepy/tweepy
import csv

#Twitter API credentials
consumer_key = "YH9hYV1jlYYIDbhhAZSPhRFVm"
consumer_secret = "Ds87pgi7huR2br9YVU4qrhm8dc4BUjaafXRopPojBFzy5603WP"
access_key = "1194870777490870272-NzV1ErlBtwc0YvP9SGA5RJZxhJtltG"
access_secret = "xyiJbmPtfxDfiiZ42WG8GlW1SBUpE5EJG0HXs6VkR0WTE"


def get_all_tweets(screen_name):
    #Twitter only allows access to a users most recent 3240 tweets with this method
    
    #authorize twitter, initialize tweepy
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_key, access_secret)
    api = tweepy.API(auth)
    
    #initialize a list to hold all the tweepy Tweets
    alltweets = []
    
    #make initial request for most recent tweets (200 is the maximum allowed count)
    new_tweets = api.user_timeline(screen_name = screen_name,count=200)
    
    #save most recent tweets
    alltweets.extend(new_tweets)
    
    #save the id of the oldest tweet less one
    oldest = alltweets[-1].id - 1
    
    #keep grabbing tweets until there are no tweets left to grab
    while len(new_tweets) > 0:
        print("getting tweets before %s" % (oldest))
        
        #all subsiquent requests use the max_id param to prevent duplicates
        new_tweets = api.user_timeline(screen_name = screen_name,count=200,max_id=oldest)
        
        #save most recent tweets
        alltweets.extend(new_tweets)
        
        #update the id of the oldest tweet less one
        oldest = alltweets[-1].id - 1
        
        print("...%s tweets downloaded so far" % (len(alltweets)))
    
    #transform the tweepy tweets into a 2D array that will populate the csv	
    outtweets = [[tweet.id_str, tweet.created_at, tweet.text.encode("utf-8")] for tweet in alltweets]
    
    #write the csv
    #with open('%s_tweets.csv' % screen_name, 'wb') as f:
    with open('%s_tweets.csv' % screen_name, 'w', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(["id","created_at","text"])
        writer.writerows(outtweets)
    
    pass


if __name__ == '__main__':
    #pass in the username of the account you want to download
    get_all_tweets("TheRock")

getting tweets before 1174657709125206021
...400 tweets downloaded so far
getting tweets before 1157435064679972863
...600 tweets downloaded so far
getting tweets before 1145709412524281855
...800 tweets downloaded so far
getting tweets before 1117869232841093119
...1000 tweets downloaded so far
getting tweets before 1099529399580442623
...1200 tweets downloaded so far
getting tweets before 1092470414251503615
...1400 tweets downloaded so far
getting tweets before 1084544638697000959
...1600 tweets downloaded so far
getting tweets before 1068317944931917824
...1800 tweets downloaded so far
getting tweets before 1051558498381762559
...1999 tweets downloaded so far
getting tweets before 1028346214473973766
...2199 tweets downloaded so far
getting tweets before 1017837624260775935
...2399 tweets downloaded so far
getting tweets before 1011592143562006528
...2596 tweets downloaded so far
getting tweets before 994644990016962559
...2796 tweets downloaded so far
getting tweets before 985577603644833791
...2995 tweets downloaded so far
getting tweets before 978387830530490367
...3195 tweets downloaded so far
getting tweets before 963457026897555455
...3239 tweets downloaded so far
getting tweets before 960582644676231167
...3239 tweets downloaded so far

In [24]:
get_all_tweets("_Propulsion")

getting tweets before 1002252413234040831
...400 tweets downloaded so far
getting tweets before 907624818480173056
...597 tweets downloaded so far
getting tweets before 880157848742883329
...687 tweets downloaded so far
getting tweets before 764220952553005056
...687 tweets downloaded so far

In [4]:
import pandas as pd
data = pd.read_csv("_Propulsion_tweets.csv")

### 1. Frequency of tweets (You’re free to choose a daily/weekly/monthly timeframe accordingly to the case)

In [5]:
datamod = data

In [35]:
datamod['Dates'] = pd.to_datetime(datamod['created_at']).dt.date
datamod['Time'] = pd.to_datetime(datamod['created_at']).dt.time

In [36]:
from datetime import datetime, timedelta

TypeError: 'Series' object is not callable

### 2. Top 5 most used hashtags

In [7]:
a = data.text.str.findall(r'#(\w+)')

In [8]:
new_df = pd.DataFrame((a[:]))

In [9]:
new_df[new_df['text'].map(lambda d: len(d)) > 0]

                                                  text
0                             [datascience, fullstack]
2                                        [hackandlead]
3                             [datascience, fullstack]
4                                        [datascience]
6                                            [BigData]
9                       [machinelearning, datascience]
10                [datascience, Capstone, projects, 7]
16                                              [8, 9]
17                                   [machinelearning]
18                     [propulsionacademy, womenplusp]
21                      [fullStack, 8, datascience, 7]
22                            [fullstack, datascience]
24                                [bigdataengineering]
25                            [education, opportunity]
26                            [fullstack, datascience]
30                                    [DataScience, 6]
34                                         [fullstack]
42                                       [Switzerland]
44                                      [7, Meetup, Z]
45                                   [machinelearning]
49                                    [6, DataScience]
50                            [fullstack, datascience]
58                                       [datascience]
61                                  [Web, Development]
64                                         [fullstack]
66                                                 [5]
72                                    [4, datascience]
73                                 [Data, DataScience]
74                                       [datascience]
75                                       [DataScience]
..                                                 ...
645            [coding, bootcamp, switzerland, Zurich]
646                             [SDSC_kickoff, Zurich]
647                              [Switzerland, Zurich]
648                                      [datacenters]
650                               [InvestorSummit2017]
651                                       [CHstartups]
652                                         [bootcamp]
653                            [fullstack, tuition, Z]
654                                   [z, datascience]
655            [codingbootcamps, switzerland, zuerich]
656                             [switzerland, zuerich]
662               [trams, buses, Zuerich, switzerland]
663                              [zurich, switzerland]
664                 [tech, startups, gadgets, travels]
665    [zurich, bootcamp, swiss, switzerland, startup]
666                         [DataScience, switzerland]
668                                      [scholarship]
669                                           [webdev]
673  [startup, scholarships, code, Zurich, switzerl...
675  [uselections, fullstack, Zurich, switzerland, ...
677  [programmer, zurich, switzerland, swiss, bootc...
678                    [zurich, switzerland, bootcamp]
679  [Python, DataScience, zurich, bootcamp, switze...
680                   [fullstack, switzerland, Zurich]
681                              [zurich, switzerland]
682                          [JavaScript, Switzerland]
683                                   [Zurich, zurich]
684                              [zurich, switzerland]
685            [zurich, Switzerland, coding, Bootcamp]
686                                           [zurich]

[449 rows x 1 columns]

In [40]:
#convert the column 'text' which is a series of lists, to a single list
hashtags_freq = list(itertools.chain.from_iterable(new_df['text']))

#lets convert all hashtags to lower otherwise when we count it will treat hashtags like
#DataScience as different from #datascience
hashtags_freq = [x.lower() for x in hashtags_freq]

In [41]:
#sort the hashtags by counting how many each hashtag appears
hashtags_freq = collections.Counter(hashtags_freq)

In [43]:
#top 5 hashtags
hashtags_freq.most_common()[0:5]

[('datascience', 141),
 ('switzerland', 59),
 ('zurich', 53),
 ('bigdata', 50),
 ('analytics', 47)]

### 3. Choose a relevant keyword and report how many times it has been used in the tweets that you scraped ( Ex: for Trump’s twitter you can search for “Wall” or “elections”)

In [47]:
hashtags_freq['datascience']

141